name: Check

on:
  push: {}
  pull_request: {}

jobs:

  go:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: make terraform-provider-android

      - name: Vet
        run: go vet

      - name: Test
        run: go test -v ./...

      - name: Format check
        run: |
          fmtdiff="$(gofmt -s -e -d .)"
          if [ -n "$fmtdiff" ]; then
            >&2 echo "$fmtdiff"
            exit 1
          fi

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraformat
        run: terraform fmt -recursive examples

      - name: Check docs updated
        run: |
          curl -L https://github.com/hashicorp/terraform-plugin-docs/releases/download/v0.4.0/tfplugindocs_0.4.0_linux_amd64.zip --output tfplugindocs.zip
          sudo unzip tfplugindocs.zip tfplugindocs -d /usr/local/bin
          make clean-docs docs
          change="$(git diff)"
          if [ -n "$change" ]; then
            >&2 echo "$change"
            exit 1
          fi
